### ISSUE TITLE
[2.5.7] Responsive settings are ignored after upgrade from 2.5.4

### ISSUE THREAD

**Issue by FrankReisenhofer** [templaza/astroid-framework#17]
Today I updated from 2.5.4 to 2.5.7.

After this upgrade the responsive settings for a layout element seem to be ignored.

The settings are like:

![image](https://user-images.githubusercontent.com/37330222/140761821-72784d36-3018-41da-8cf9-e9513271e548.png)

But this settings are completely been ignored and the element is also shown on large and extra-large screens.

Any ideas what might cause this?

**Comment by sonvnn** [comment]
Thanks for feedback! I will check this issue in the next 24h. Please wait for update.

Thanks,
Sonny

**Comment by Joomlaplates** [comment]
Yes, I can agree, its a bug.
There is a missing a css class in the PHP code and a missing css code in the css file.
```
@media (min-width: 1400px) { 
  .hideonxxl {
    display: none !important;
  }
}
```
![hide](https://user-images.githubusercontent.com/71080509/140820973-2d7cf80b-b185-4197-b9f7-374a0884a5e1.jpg)

**Comment by sonvnn** [comment]
Hello @FrankReisenhofer @Joomlaplates 
Thanks for your support. I fixed this issue at #18 
Please help me check it again. I will update version 2.5.8 as soon as you confirm that issue was solved.

Best Regards,
Sonny

**Comment by FrankReisenhofer** [comment]
Hello @sonvnn,

Thanks for your quick fix. 

I am ready to perform some tests once the new version is released.

**Comment by sonvnn** [comment]
Hello @FrankReisenhofer 
You can download Master branch at https://github.com/templaza/astroid-framework/archive/refs/heads/master.zip
Let's upload to your site -> clear template cache and check it.
Please let me know if your issue still happen.

Best Regards,

**Comment by FrankReisenhofer** [comment]
Hello @sonvnn 

I installed the master branch version.

But it is not yet working:

Please have a look at [1]. You will still see two slideshows.

[1]
https://reisenhofer.de/index.php/de/

**Comment by sonvnn** [comment]
Hi @FrankReisenhofer ,

You should try to enable "Hide on Extra-Extra-Large Devices" in Responsive tab. 
![Screen Shot 2021-11-09 at 17 42 19](https://user-images.githubusercontent.com/3204103/140910188-7eb538f8-0ef5-4bf2-a0ae-71a9a435293f.png)
Please see my image.

**Comment by FrankReisenhofer** [comment]
Hello @sonvnn ,

That are exactly my settings for this field :-). See my first screenshot.

As I have currently no further time for performing tests I installed again version 2.5.4.

-> The side is back to normal.

In the future I will wait for green light from @Joomlaplates before installing a newer version.

**Comment by biobill** [comment]
May I ask who is supporting Astroid? Templaza or Joomlaplates?

**Comment by Joomlaplates** [comment]
Both are supporting Astroid, but Templaza is creating the Gits and update the files. Otherwise it gets confused, if both a wre working on files.

**Comment by biobill** [comment]
That's clear enough. Thanks!

**Comment by Joomlaplates** [comment]
> 
> 
> Hello @sonvnn ,
> 
> That are exactly my settings for this field :-). See my first screenshot.
> 
> As I have currently no further time for performing tests I installed again version 2.5.4.
> 
> -> The side is back to normal.
> 
> In the future I will wait for green light from @Joomlaplates before installing a newer version.

Not a bad idea! We are still testing the Version 2.5.7 and ofc there are still some bugs.
https://www.joomlaplates.de/forum/news-updates-und-informationen/117-astroid-2-5-7-changelog.html

**Comment by sonvnn** [comment]
Hello @FrankReisenhofer 
I mean you missed XXL option. You have to go to your layout configure and enable "Hide on Extra-Extra-Large Devices". I just added this in latest version.
![Screen-Shot-2021-11-10-at-09 38 15](https://user-images.githubusercontent.com/3204103/141040017-69d3fcdf-241b-4d1e-9f84-63e73da8aa11.png)

**Comment by Joomlaplates** [comment]
I can agree, the **hideonxxl** is working now.
Maybe enable the debug function in astroid plugin to delete the cache and compile the scss again

**Comment by sonvnn** [comment]
Yeah, You need clear template cache to re-compile scss again.
![screenshot-joomla templaza com-2021 11 10-16_19_26](https://user-images.githubusercontent.com/3204103/141085740-5adc95ea-6058-4102-b276-afb9e0bbbf55.png)

**Comment by sonvnn** [comment]
This issue was resolved at #20 
Please help me update Astroid v2.5.8.
Thank you :)

**Comment by FrankReisenhofer** [comment]
Hello @sonvnn ,

Thanks for your information. I updated to 2.5.8 and can confirm:

After using the xxl option correctly the side is back to normal :-).
