### ISSUE TITLE
Astroid 2.6.0 fonts folder not working anymore

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#210]
Hi Sonny, big problem.
The **fonts** folder is not working anymore. I think it is because you move some folders from template to media folder.
Many people from EU use this trick and add their own fonts into this folder to avoid loading from Google fonts. 
Here is the description what I mean ( switch to english)
https://www.joomlaplates.de/joomla-tips-und-tricks/google-schrift-deaktivieren.html
Greatings Peter

AND btw you cant downgrade from Astroid 2.6.0 to 2.5.20 because all files are already moved and not copied to **Joomla/media** folder

**Comment by sonvnn** [comment]
Hi @Joomlaplates
I fixed local font in https://github.com/templaza/astroid-framework/commit/2cd14d069b0173637c699c45f4e850cf076bc52f

Please help me check it! If everything is good. I will release fixed bug version.

Best Regards,
Sonny

**Comment by sonvnn** [comment]
Please help me download developer here https://github.com/templaza/astroid-framework/archive/refs/heads/developer.zip

**Comment by deltapapa01** [comment]
Hey Sonny, thank you very much for your work and the quick help with problems :-)
I can confirm Peter's problem, and I installed developer.zip and the fonts are loading properly again. Only the version is still shown as 2.6.0, but that will surely come in the new version.
But, doesn't it make more sense to put the Fonts folder under images/astroid_template_zero/fonts?
For example, you have the option of embedding fonts locally with the JCE browser direct from Joomla, because the JCE browser and similar tools cannot go to the root level.
WBR from germany,
deltapapa

**Comment by sonvnn** [comment]
Hi @deltapapa01 

I updated feature load font from images/{template}/fonts folder in https://github.com/templaza/astroid-framework/commit/d57285440aea68f2d0f95a688bad5318c1cb9cb6. You can download developer branch for testing.

Thanks & Best Regards,
Sonny

**Comment by deltapapa01** [comment]
Hi, i download and test the dev branch, in the first look it looks good :-)
Now, can i delete the fonts folder under media?

WBR,
deltapapa

**Comment by sonvnn** [comment]
You can use both of them. No need action. System will check both of image and media folder

**Comment by deltapapa01** [comment]
Okay, i delete the folder under /cms/media/templates/site and make a new folder under /cms/images/astroid_template_zero/fonts. But now, the fonts will not shown as custom fonts in astroid beackend....

WBR,
deltapapa

**Comment by Chacapamac** [comment]
Just join the discussion as updating to 2.6.0 cause big difficulties for me to

**From **deltapapa01****

> But, doesn't it make more sense to put the Fonts folder under images/astroid_template_zero/fonts?
> For example, you have the option of embedding fonts locally with the JCE browser direct from Joomla, because the JCE browser and similar tools cannot go to the root level.

**This is serious business here...**
—————————————————————————————————————
**1.  put the Fonts folder under images/astroid_template_zero/fonts?**

Even that way make no sense, it will clutter the “images” folder with folders and files that have nothing to do with images
—————————————————————————————————————

—————————————————————————————————————
**2.  For example, you have the option of embedding fonts locally with the JCE browser direct from Joomla, because the JCE browser and similar tools cannot go to the root level.**

**I use JCE forever and will use it for a long times in the future as it is the best editor for Joomla**
With JCE you can make a WYSIWYG editor BECAUSE it can load the **template CSS**, **custom local fonts**, Awesome icons... directly in the editor windows.

**For me this is primordial, I will not use a framework that does not permit that..**
—————————————————————————————————————

**Comment by sonvnn** [comment]
> Okay, i delete the folder under /cms/media/templates/site/fonts and make a new folder under /cms/images/astroid_template_zero/fonts. But now, the fonts will not shown as custom fonts in astroid backend....
> 
> 
> 
> WBR,
> 
> deltapapa

May you send me your admin acc via sonlv@templaza.com? I will help you check it

**Comment by Joomlaplates** [comment]
Hi Sonny, I am on testing and I run in different problems.
**Astroid Dev branch 2.6.1**
1.) The params folders with json files in it makes problems and Astroid config istn loading.
2.) When I add manually the fonts folder into Template folder the Astroid is not loading anymore.
....
Finally the child theme is usefull for 1% of the user but makes so much trouble. I think a good idea would be, copy all the files to media folder if the user is using child theme and not before.
...
Anyway another idea: Can you add an upload button for fft fonts in the backend?
..
Have a nice day, weekend, greatings Peter

**Comment by sonvnn** [comment]
In Joomla 4. fonts folder will move to media folder. You have to upload ttf file to media/templates/site/{your-template}/fonts

Please help me try it again!

We are forward to Joomla 4.3 and Joomla 5 in the next year. So we need prepare to follow Joomla structure, asap

**Comment by sonvnn** [comment]
Anyway another idea: Can you add an upload button for fft fonts in the backend?

For this idea. You can use com Media upload your ttf font to images/{your-template}/fonts

It will load perfectly in the backend

**Comment by Chacapamac** [comment]
Ok, if I follow the discussion, Astroid 2.6.0 is not Joomla 3 compatible?

**Comment by Joomlaplates** [comment]
Hi Sonny, 
yes everything is working now with Astroid 2.6.1 but fonts must be stored in images/{your-template}/fonts now.
Thanks a lot, Sonny

**Comment by Chacapamac** [comment]
@Joomlaplates — 2 questions
1. When you say —> images/{your-template}/fonts
Do you mean the Root Joomla “images” folder ?

2. Is this can be loaded in the JCE Editor?

**Comment by sonvnn** [comment]
> Ok, if I follow the discussion, Astroid 2.6.0 is not Joomla 3 compatible?

Astroid 2.6.1 is fully Joomla 3 Compatible.

**Comment by Chacapamac** [comment]
You guys scared me for a second .......

**Comment by sonvnn** [comment]
> Hi Sonny, yes everything is working now with Astroid 2.6.1 but fonts must be stored in images/{your-template}/fonts now. But Joomla media manager is not allowed to upload ttf files. Thanks a lot, Sonny

You can configure com media to allow upload ttf files. Please check my screenshot.
![media_configure](https://user-images.githubusercontent.com/3204103/194710964-25f0b5a5-86f7-4cc1-98c5-ab5dc5edef1c.png)
![font_upload](https://user-images.githubusercontent.com/3204103/194710974-857fa9e0-983f-4894-a9dd-637350c2f318.png)

Let's try with it and give me your opinion :D

**Comment by sonvnn** [comment]
> You guys scared me for a second ....... @sonvnn —. Are the templates update (Zero & One) compatible?

Sure let's try to download 2.6.1 and upload to your server. Feel free to give me your feedback.
Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Same link above (developer branch)?

— I guess, for a website with local custom fonts I have to follow what is said here and change my call in my —> astroid_template_zero > scss > custom > custom.css ?

**Comment by Joomlaplates** [comment]
> @Joomlaplates — 2 questions
> 
>     1. When you say —> images/{your-template}/fonts
>        Do you mean the Root Joomla “images” folder ?
> 
>     2. Is this can be loaded in the JCE Editor?

Yes Joomla Root folder/images

**Comment by Chacapamac** [comment]
Thanks @Joomlaplates , I find that a bit crappy as user will see that {your-template} folder in their images manager that already have others Joomla system folders (like banners) — At least with JCE you can add a clean root image user folder to clean the clutter.

JCE will still be able to load the Astroid templates css in (as example) —> astroid_template_zero > css ?

**Comment by deltapapa01** [comment]
Hi Sonny,
okay, i sent you the access data for my test site.
I have loaded the fonts via ftp into the folder /cms/images/astroid_template_zero/fonts, but they are not displayed in the Astroid backend or under Media. But they are online.

WBR,
deltapapa

**Comment by sonvnn** [comment]
Hi @Joomlaplates @Chacapamac @deltapapa01 

I upload my screenshots here. I hope you understand how to setup local font on Astroid 2.6.1

1. You can upload `ttf` to `media/templates/site/{template}/fonts` or `images/{template}/fonts`
![local_font_folder](https://user-images.githubusercontent.com/3204103/194711959-d1492108-7f07-4bbc-ae0e-bb2e7b731bef.png)

2. Go to template option > typography > choose your custom font
![load_backend](https://user-images.githubusercontent.com/3204103/194712062-695b93bd-6a5d-41fe-adb0-c79b025e97bf.png)

3. Go to front-end and check it.
![local_font_result](https://user-images.githubusercontent.com/3204103/194712099-e34ec5ba-b670-4f70-8e10-97e527786238.png)

Let's check it and give me your feedback.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Great, I will test all that with Joomla 3 & 4

**Comment by deltapapa01** [comment]
Hi,
nope, is not working:

![Screenshot 2022-10-08 163813](https://user-images.githubusercontent.com/19833064/194712955-7b689b66-db28-43df-ba81-24fc829ab7fa.jpg)

![Screenshot 2022-10-08 163821](https://user-images.githubusercontent.com/19833064/194712956-4575aa2f-7a99-4656-9081-0f4ae3b045dd.jpg)

![Screenshot 2022-10-08 163828](https://user-images.githubusercontent.com/19833064/194712959-d1572516-b509-4e15-818b-aeb5e85cb705.jpg)

**Comment by sonvnn** [comment]
@deltapapa01 It's very strange for me. It works perfectly on my site. Please use media/templates/site folder instead of image folder . I will check it this issue on next Monday.

**Comment by sonvnn** [comment]
@deltapapa01 I found this issue. I fixed it in https://github.com/templaza/astroid-framework/commit/9dba5e2f202895b1a3384d7ae4b8db964629d11d

I updated this on your site. Please help me check it.

Thanks,
Sonny

**Comment by Joomlaplates** [comment]
Yep I agree, both methodes are not working.
I tried with dev branch of Astroid
..
```
JoomlaRoot/images/template-name/fonts/
JoomlaRoot/media/templates/site/template-name/fonts/
```
Astroid is not even loading when I use this folders.

**Comment by Chacapamac** [comment]
You should pull 2.6.0. until all that is resolve.

**Comment by sonvnn** [comment]
> Yep I agree, both methodes are not working.
> 
> I tried with dev branch of Astroid
> 
> ..
> 
> ```
> 
> JoomlaRoot/images/template-name/fonts/
> 
> JoomlaRoot/media/templates/site/template-name/fonts/
> 
> ```
> 
> Astroid is not even loading when I use this folders.

I solved issue on @deltapapa01 's website. Now his site is working. If your site does not work, let's send me your admin account via sonlv@templaza.com. I will check in on Monday.

Best regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi Sonny,
driving me nuts. I tried on my developer site online and its working. On my localhost its not working. Same PHP same situation, dont ask me why. But I will find the reason.
..
But which version of Astroid is working now ? The dev or the master?
Happy Sunday Sonny.

**Comment by deltapapa01** [comment]
Hi @sonvnn 
i check out my site and is working now.
So, i will test the dev on another test site later and come back.
WBR and happy sunday :-)

**Comment by sonvnn** [comment]
> Hi Sonny, driving me nuts. I tried on my developer site online and its working. On my localhost its not working. Same PHP same situation, dont ask me why. But I will find the reason. .. But which version of Astroid is working now ? The dev or the master? Happy Sunday Sonny.

Developer branch always is latest version. Let's check it.
Best Regards,

**Comment by Chacapamac** [comment]
**Just install Developer branch** — Frontend of website gone with error
![Develloper-Branch](https://user-images.githubusercontent.com/1907276/194895780-40274ed4-1471-4b52-bf4d-a7d08bfa7c0a.jpg)

**Comment by sonvnn** [comment]
> **Just install Developer branch** — Frontend of website gone with error
> 
> 
> 
> ![Develloper-Branch](https://user-images.githubusercontent.com/1907276/194895780-40274ed4-1471-4b52-bf4d-a7d08bfa7c0a.jpg)
> 
> 

May you send me your admin acc? I will check it when I back to office tomorrow.

Thanks & best regards,
Sonny

**Comment by Chacapamac** [comment]
Thank You Sonny, I find the problem but all my astroid websites will not work with this version as I always use a custom.css file.
**This is cause by adding a normal custom.css file in a custom folder the way it was done before**
  templates > astroid_template_zero > scss > (added) custom > (added)custom.scss

**Removing the file bring back the frontend** but no more custom css for the website. 
I guess it have to do with that moving of files and folders to the media folder (same with the custom fonts)

_This is a big problem as many websites will be broken by this...._

Now I will try the custom fonts fix to see if it work and pickup by JCE to permit a WYSIWYG editor. 
**You need to see the correct fonts, styles and css in the editor window**

**Comment by sonvnn** [comment]
Sure! I will check it asap tomorrow. May you re-send me an JCE pro via sonlv@templaza.com? I will install and test it.

Thanks & Best regards,
Sonny

**Comment by Joomlaplates** [comment]
Anyway, ofc we know now that the files and folders are moved/copied because of the new child template.
**But please tell us, if we can still use the folders in the template folder:** and the priority request where astroid is looking for them.
And its confusing, some files are are in images, some in media folder and some in template...
Greatings Peter

**Comment by sonvnn** [comment]
Hi Peter,

Images, Media or Template folder is option. You can choose one of them as your prefer. If you want store custom font in template/{your-template}/fonts, you can use it and ignore "media" or "image" folder. Your site will works normally.

I noted that it is option for dev only. 
For example: 
- @deltapapa01 like "images" folder he will save tff in "images/{template}/fonts"
- You like "template" folder you will save tff in "templates/{template}/fonts"
- I like "media" folder I will save tff in "media/templates/site/{template}/fonts"

It depends of your favorite. System will check all way. Don't care about "image" or "media" if you don't like them. They are options only.

Thanks & Best regards,
Sonny

**Comment by Joomlaplates** [comment]
Hi sonny, great thank you.
I think this is not only for fonts, its for scss or css files too

**Comment by sonvnn** [comment]
> Hi sonny, great thank you.
> 
> I think this is not only for fonts, its for scss or css files too
> 
> 

If you find any issue. Please reproduce issue detail step by step. So I can understand and fix it.

Astroid 2.6.1 is stable right now

Thanks & Best regards,
Sonny

**Comment by Chacapamac** [comment]
**TEST 1**
_On a live test website_
- Last Joomla 4
-  Astroid Dev branch

• Test using the “**media**” folder for **custom fonts** and **custom.scss** and effect in **JCE Editor**
![folder-media](https://user-images.githubusercontent.com/1907276/195123305-b987097b-aee7-4add-8db9-85a289ddd63d.jpg)

**RESULTS**
— Fonts are displaying perfectly, body font are Source Sans and all Header are Barlow
http://joom4-astro.graf-test.ca/
— Custom scss working perfectly and compiled correctly in the css folder

**Problems ——————————————————————_**
**1•** I do not see the “**Custom Fonts**” with **Source** & **Barlow** available in the Template Manager typography section if I want to use them as “Custom” ???

![0AED1CF8-625F-4758-8798-6E1BF8E74C6E](https://user-images.githubusercontent.com/1907276/195130312-528568b0-7b2b-473f-9962-f7f3ae4be922.jpeg)

**2•** For sure all the capacity of JCE to show the correct custom fonts and all the css of the website in the editor window making JCE a WYSIWYG editor is not working. 
**— I will check next if I can make it work using JCE settings**. 
I doubt I can as JCE can only target **ALL** css in the Your_Template / css / ALL .css files  (it target also generated css files and use it to display WYSIWYG in the editor window)
— I don’t think it can do the same thing in the media folder????
![jce](https://user-images.githubusercontent.com/1907276/195130557-3b5fcd78-3ef9-47eb-b9a9-336ba6045848.jpg)

**Comment by sonvnn** [comment]
@Chacapamac Thanks for testing.

1. Astroid can not read font in sub folder. So please put ttf file in fonts folder without sub folder. Actually, I follow documents of Peter ( @Joomlaplates ). It is first time I try to use custom font ;). With custom font you don't need add to custom.scss. Just insert ttf files to fonts folder and choose them in admin. System will detect and load them on front-end.

2. I will check it tomorrow. I got JCE pro v2.9.29 that you sent me before. I will follow issue of @fontanil and check it.

Best regards,
Sonny

**Comment by sonvnn** [comment]
I have to sleep now. Just tired after a long day. Good night to all.

**Comment by Chacapamac** [comment]
Good Night Sonny!

Just try to upload my fonts files directly to the media/fonts folder  (I’m not using **ttf** because it’s the old un-efficient fonts format), I’m using the newer **woff** format.

**Result:** the template manager refuse to open with a lots of errors.....

![error](https://user-images.githubusercontent.com/1907276/195155365-0d3022f1-cf1e-4878-b88d-f48ef076a989.jpg)

**Note:** I remove all custom css and just drop the fonts files and clear all caches to be sure.
![no-more](https://user-images.githubusercontent.com/1907276/195155207-867d92b1-2294-4b39-8b1b-94e3af97c5f3.jpg)

**Comment by fontanil** [comment]
Hi,

Did you try that folder?
![image](https://user-images.githubusercontent.com/8665970/195158070-02b597b8-0683-4e77-aed6-992dd92f7b89.png)

**Comment by sonvnn** [comment]
Hi @Chacapamac,

Astroid supports 'otf', 'ttf', 'woff' only. Please help me remove woff2 files.
![Screen Shot 2022-10-12 at 16 53 22](https://user-images.githubusercontent.com/3204103/195311755-f7ee33d9-ba5a-45c4-90d0-bc6b614e4783.png)
![Screen Shot 2022-10-12 at 16 54 03](https://user-images.githubusercontent.com/3204103/195311890-08f41d99-63a3-4a76-b35e-c0821a309659.png)

I test on my localhost and it works perfectly.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
@sonvnn ,
I just cleanup everything and try again

**This is my Astroid setup on this test website**
![Astroid](https://user-images.githubusercontent.com/1907276/195601703-15624eed-c9cd-46d3-95d1-d9a8355dbee1.jpg)

— Before doing my test, I clean all caches _(Astroid, Joomla, Browser)_ and reload the front page before going to the administration to re-generate the compiled css
— Also no custom.scss and no custom fonts or custom.scss in the normal **templates/astroid_template_zero** folder
— I’m in the right **media/templates/sites/astroid_template_zero/fonts** folder
— I try 2 woff files (Souce-sans-pro & Barlow) **that work perfectly on one of my website**

![media-folder-no-font](https://user-images.githubusercontent.com/1907276/195604399-39ffc0a1-929e-4f73-aaf1-b34de43fe617.jpg)

**Adding woff**
![add-woff](https://user-images.githubusercontent.com/1907276/195604843-a4c2a985-0802-42b5-a0b1-4265960364d0.jpg)

**Results:**
100% reproducible, any woff file added bring errors in the template zero administration, no woff files, no errors

**Comment by sonvnn** [comment]
@Chacapamac please send me your admin acc via sonlv@templaza.com. I will help you check it.

Thanks & Best regards,
Sonny

**Comment by Chacapamac** [comment]
Just Send, take your time Sonny. No rush!

Good Day to all Astroid fans!

**Comment by sonvnn** [comment]
I got it. I will check it tomorrow.

Thanks,
Sonny

**Comment by sonvnn** [comment]
Hi @Chacapamac ,

This issue happens because Deprecated issue with PHP 8.1. I updated FontLib to fix Deprecated issue on https://github.com/templaza/astroid-framework/commit/5e41a2494c127cf19a57c578127dcd1ffcc2714b

Now, Your site works well. Please help me check it again.
Thank you for your cooperate!

Best Regards,
Sonny

**Comment by sonvnn** [comment]
> Thanks @sonvnn 
> 
> 
> 
> Are you making that move (from folder “**templates**” to “**medias**”) for the new Joomla 4 “**Child Templates**”?
> 
> 
> 
> Good Day!
> 
> 
> 
> **Also, the first error seem to come from that line of code:**
> 
> ![Screen Shot 2022-10-13 at 9 47 58 AM](https://user-images.githubusercontent.com/1907276/195615483-c5b8e958-64dd-4928-844d-b4b4e51569c0.jpg)
> 
> 

Astroid 2.6 will move astroid, params and fonts folders from "template" to "media"

**Comment by Chacapamac** [comment]
**I decide to go deeper to understand what we are doing here and why, and also answer my own question.........**
**Everybody**, _if one of my statement is wrong, please correct me!_

**1. To respond to my question about the stuff moving to the “media” folder????**
— If I understand well? From Joomla 4.1, Template providers can decide to permit the possibility to create Child Templates with their Framework/Templates. 
— Joomla onboard Template, Cassiopea have that possibility.
— Astroid have now the same possibility

— To permit this possibility you have now 2 places where template files reside
1. The normal **Joomlaroot > templates > yourtemplatename** folder
2. The  **Joomlaroot > media > templates > site > yourtemplatename** folder

**In the case of Cassiopeia**
• In the **Joomlaroot > templates**
_**Note:** I create a Child template for Cassiopeia and Template One just to understand_

![Screen Shot 2022-10-14 at 6 01 23 PM](https://user-images.githubusercontent.com/1907276/195952998-9ae03616-1713-4ea6-98e7-16211a0e0cf8.jpg)

• In the **Joomlaroot > media > templates > site**
![media](https://user-images.githubusercontent.com/1907276/195953103-ef3e6a34-f219-4d09-a2c2-5a900ccb1332.jpg)

**QUESTION:** ——————————————————————————————
**In the case of Joomla Cassiopeia**, the parent important files (css,images,js, scss) are **completely move to the “media” folder**

**In the case of Astroid Zero & One**, the parent important files (css,images,js, scss) are mostly duplicated to the “media” folder**

@sonvnn , **Can you explain the difference between Cassiopeia & Astroid?**
 ——————————————————————————————

I take my infos on Child templates from:
**• Deep dive into Joomla Child Templates**
https://magazine.joomla.org/all-issues/may-2022/a-deep-dive-into-joomla-child-templates. I will prepare an easy to understand overview of all that and also how to work it out with JCE editor that can be use _(if you want)_ for the Astroid Users out there.

**Comment by sonvnn** [comment]
Hello @Chacapamac 

> My question is, if that move is done by Joomla itself and need to be done by ALL Templates providers or only by Astroid?

Now Joomla supports load file both of `template` and `media` folder. But In Joomla 5 will remove old MVC model and support `media` folder only. The template providers should prepare to update their templates for that. Please check Joomla Roadmap.

> I ask the question, because, JCE Editor seem to not be able, so far ( I’m discussing with the developer of JCE, Ryan on that problem right now!) to display (as it was when the CSS was in the “templates” folder) all the css (compiled and all otthers) in its edition window, loosing the so important WYSIWYG (What You See is What You Get) ability of JCE.

In the next Astroid version will support load `template.css` from `media/templates/site/{template}/css`. So JCE can load style list of Astroid templates even when you use old version. I update it in the commit https://github.com/templaza/astroid-framework/commit/aaaa5a9d0e3b4e09390f947415a6a14ff3002603 and here https://github.com/templaza/astroid-framework/blob/developer/framework/library/astroid/Document.php#L1140-L1142

> In the case of Astroid Zero & One, the parent important files (css,images,js, scss) are mostly duplicated to the “media” folder**

This happen because you install Zero in old site with old files from Zero or One template version. Please download fresh Joomla from Joomla.org and install Zero or One template to that site. You can see they are not duplicated anymore. Please check sceenshots of fresh Install below:

- Here are Zero parent and child template in `templates folder`
![tempalte](https://user-images.githubusercontent.com/3204103/195967049-727d174a-ba2d-47a5-8f8c-b12d0897f728.png)
- Here are Zero and Cassiopeia child templates in `media folder`
![mediafolder](https://user-images.githubusercontent.com/3204103/195967125-127691e4-2f97-48ce-aa95-770ec52702c2.png)

**I noted that please install on a fresh Joomla with first install of Astroid and Zero or One. No update in your old Astroid site.**

Please help me check it!
Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Thank You @sonvnn for the detail answer. It answer all my question.

Good Weekend!

**Comment by Chacapamac** [comment]
@sonvnn, you said

> This happen because you install Zero in old site with old files from Zero or One template version. Please download fresh Joomla from Joomla.org and install Zero or One template to that site. You can see they are not duplicated anymore. Please check sceenshots of fresh Install below:

You understand that it is not possible to do this with an existing website without having to rebuild the website almost from scratch, this is not a solution for complex website.
 
**What I’m searching now is a safe way to pass an existing website to this new structure.**

**2 questions:**
• What exact framework, templates update versions operate this change?

• If you have any hints how to achieve that, your welcome?

**Comment by fontanil** [comment]
On some sites where the template was moved to media, As a precaution I made a local copy of the old template/astroid_template_one (or zero) folder then I deleted all the sub-folders except html and language

**Comment by sonvnn** [comment]
> @sonvnn, you said
> 
> > This happen because you install Zero in old site with old files from Zero or One template version. Please download fresh Joomla from Joomla.org and install Zero or One template to that site. You can see they are not duplicated anymore. Please check sceenshots of fresh Install below:
> 
> You understand that it is not possible to do this with an existing website without having to rebuild the website almost from scratch, this is not a solution for complex website.
> 
> **What I’m searching now is a safe way to pass an existing website to this new structure.**
> 
> **2 questions:** • What exact framework, templates update versions operate this change?
> 
> • If you have any hints how to achieve that, your welcome?
> 
> For now all my existing websites are on:
> 
> * Framework: 2.5.20
> * Zero: 2.5.19

Astroid 2.6 will move Astroid, Params and Fonts folder only. Because some old templates (from JoomlaPlate, Joomdev and TemPlaza) are not ready for Child-template. They need time to Joomla Template provider update template xml structure and scss code. If Astroid move all folders to Media folder, they might break customer site. 

In Zero and One template will create all folders except "html" to Media folder. And Astroid will detech folders both in Media and Templates. If a folder (ex: scss) is exist in Media, Astroid will use it instead of "scss" folder in templates. So, don't worry about old folders in templates folder. They will not use anymore until folders in "media" exist. 

If you don't like to see them, you can remove them manually. Please check if a folder is available in Media folder, you can remove it in "templates" folder. That is the solution.

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Thanks a lot @sonvnn for the clear and complete explanation.

I test it myself and I’m writing an article concerning the new template child possibility and the necessary update to Joomla 4.1+ and Astroid 2.6.0+ _(You can have it for the Astroid website if you like it at the end)_

I test with a new website and update from —> Joomla 4.0 — Astroid 2.5.20 / Astroid Template Zero 2.5.19
to
Joomla 4.2.4 — Astroid Framework & Template 2.6.2

**This is my test Astroid Zero setup:**
![Before_Joomla_4-1-templates](https://user-images.githubusercontent.com/1907276/199736281-0262a184-84c1-4ba0-af1d-35425793b4ad.jpg)

**WHAT I FIND** —————>  _( Tell me if I’m right? )_
**• Updating to Joomla 4.1 or higher** 
— Does nothing to — Astroid 2.5.20 / Astroid Template Zero 2.5.19
— No changes in both “media” & in the normal “templates” folder for Astroid Template Zero 2.5.19
— Changes in both folders to Cassiopeia. Folders “css, images, js, scss” moves to media

**RESULT:** No problem with frontend website / custom fonts / custom sccs 

**ONE QUESTION HERE:** 
If I first install/update **Astroid Framework 2.6** on **Joomla 4.0** are the folders still move to the **“media”** folders or they will be move if I update Joomla? 

——————————————————————————————————————

**• Updating to Astroid Framework 2.6.0 or higher** 
— Changes to both “media” & the normal “templates” folder for Astroid Template Zero 2.5.19

• In “**templates**” folder
— Folder “astroid” is move to “media”
— the “css” folder is copy from the “templates” folder (even with already compiled css), but some files are NOT copied/move to the “media” folder (isis folder) 
— Custom “fonts” folder is move to “media”
— Folder “param” is move to “media”
— The folder “scss” containing also my optional “custom.scss” are not move/copy to folder “media” but seem to take effect on website frontend

**RESULT:** No problem with frontend website / custom fonts / custom sccs 

**ONE QUESTION HERE:** 
I was expecting the “scss” folder to be move to “media”, can you explain, seem to still work in frontend? 


** QUESTION:**  (I am testing that after)
What happen if you update to Astroid 2.6.0 on a existing website with still Joomla 3.10.11?

Good Day for the Astroid Fans!

**Comment by sonvnn** [comment]
@Chacapamac I will answer you questions one by one, tomorrow. In the next time if you have a question, please create a new topic on discussion. It will help others find their solution. This issue is closed. It is very difficult to follow up.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
I’m testing all that now... Take Your Time no rush!
Have a great Day!

**Comment by Chacapamac** [comment]
@sonvnn  **You don't have to read my last post**, I answer my own question about the “scss“ folder with my new tests

> The “**scss**” folder in the “template” folder is move only if the Astroid template is updated to a template version that support **“Child Template”**  2.6.0 UP

**Now I will try to update a complex Joomla 3 website**, If you have any hints, you're welcome

Just after I write this, I will send you a pdf by an email name “Child Template Update” where I wrote in detail the process. _(it’s only a draft...)_

— The only “bug” that I find so far is that, if you have a “custom” folder with a “custom.scss” when you update the template to a “Child Template” ready Astroid, you get a 500 error in frontend — You need to manually move the “scss” “custom” folder (with the “custom.scss”) to the “media” folder.
**Maybe its due to having the “custom.scss” inside a folder (“custom”)???**
It will be great if the file “custom.scss” (or custom folder) are automatically move to the “media” folder

**Comment by sonvnn** [comment]
Hi @Chacapamac 

> If I first install/update Astroid Framework 2.6 on Joomla 4.0 are the folders still move to the “media” folders or they will be move if I update Joomla?

It depends of your xml file. Please check your xml structure https://github.com/templaza/astroid-framework/blob/zero-template/templateDetails.xml#L27:L33

> I was expecting the “scss” folder to be move to “media”, can you explain, seem to still work in frontend?

If you update Astroid 2.6 only "templates/your-template/scss" is still work normally. You don't need move it to "media". If you would like to move it to "media" please check your scss files to correct `@import` command. Because the location change will make crash "500 error" issue.

> What happen if you update to Astroid 2.6.0 on a existing website with still Joomla 3.10.11?

You can update Astroid in Joomla 3.10.11 without any issue.

> The only “bug” that I find so far is that, if you have a “custom” folder with a “custom.scss” when you update the template to a “Child Template” ready Astroid, you get a 500 error in frontend — You need to manually move the “scss” “custom” folder (with the “custom.scss”) to the “media” folder.

You have to place custom folder in same location with `scss/style.scss` If you want to move custom to "media" you have to move all scss files to "media".

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Sorry @sonvnn  if use this post to talk about that. I did, because the original fonts bug was due to this new structure to allow Child template. Thank You to help me here.

> It depends of your xml file. Please check your xml structure
Really interesting, thank You

I think I’m OK from there — Thank You!

**Comment by Joomlaplates** [comment]
Hi,
I tried out with scss and custom.scss.
For me everything is working even with @import cslls and fonts folder.
This is the folder structure of the child theme in media fodler
![scss](https://user-images.githubusercontent.com/71080509/200125714-d2f85ae2-bc6e-4a28-a5c9-ff0cbf3f741b.jpg)
