### ISSUE TITLE
Problem with a background video

### ISSUE THREAD

**Issue by enserk** [templaza/astroid-framework#432]
<img width="1160" alt="inderjoomlastruktur" src="https://github.com/templaza/astroid-framework/assets/149680062/f2d3877a-fc67-44d4-b6f4-11a9e44306fd">
<img width="1236" alt="imtamplate" src="https://github.com/templaza/astroid-framework/assets/149680062/53f477f0-45f6-447d-acae-068b09983114">
Hi there! I have the problem that i cannot inster a backgroudn video. I have uploaded the video to the media section in Joomla. when i go to the layout section in the template and want to set up the video non of the files is shown. what can i do to be able to select the vide files?

**Comment by sonvnn** [comment]
Hi, I fixed this issue in https://github.com/templaza/astroid-framework/commit/add93aab4a0bd305d6249f3d2fd312fd81e1819a

Please help me re-download v3 branch and retest again https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip

Thanks & Best Regards,
Sonny

**Comment by enserk** [comment]
Hi! Perfect it works! Thanks a lot!
One more questeion: Is it possible to configure it that the shown video is not static situated but dynamic as the background pictures so that you can see not only one excerpt when scrolling down?

**Comment by Joomlaplates** [comment]
> Hi! Perfect it works! Thanks a lot! One more questeion: Is it possible to configure it that the shown video is not static situated but dynamic as the background pictures so that you can see not only one excerpt when scrolling down?

No, not possible

**Comment by Joomlaplates** [comment]
> Hi, I fixed this issue in [add93aa](https://github.com/templaza/astroid-framework/commit/add93aab4a0bd305d6249f3d2fd312fd81e1819a)
> 
> Please help me re-download v3 branch and retest again https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip
> 
> Thanks & Best Regards, Sonny

Hi Sonny,
1.) Its still not possible to select an image, see picture attached
2.) I used your donwload link. But please if you update the Astroid, change the version number > 
- 3.0.3.1
- or 3.0.3a or 3.0.3b
- Otherwise nobody knows what is the newest version and we get all confused.
- Regards Peter. Great JOB!
- 
![Screenshot_1](https://github.com/templaza/astroid-framework/assets/71080509/d9e6c36b-4172-419f-8b17-2ab92dc706ae)
