### ISSUE TITLE
SmoothScroll is not working anymore

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#860]
Astroid 3.1.7
Template TWO
Joomla 5.2
..
The Smoothscroll from menu is not working anymore.
https://compassionate-bardeen.85-214-95-104.plesk.page/

Regards Peter

**Comment by Joomlaplates** [comment]
You can fix it with adding following code, see picture
![scroll](https://github.com/user-attachments/assets/9d46dc63-ddbb-4244-aa51-692ca0768821)
The script found on Codepen
https://codepen.io/cferdinandi/pen/wQzrdM

**Comment by WM-Loose** [comment]
I can confirm this and Peter's solution works. 
Until it is solved, all our customers should deactivate Smoothscroll.

**Comment by WM-Loose** [comment]
It works with Chrome and Edge. 
So we checked Firefox again and found that the smooth gliding function was not activated there. 
After activating it, it now works in Firefox too.

FF
options /surfing / smooth gliding = on

**Comment by sonvnn** [comment]
@Joomlaplates @WM-Loose I am sorry that I cannot reproduce the issue you mentioned on Chrome, Firefox, Safari. I have tried on different computers in my company and cannot find the problem here. Can you please help me create a video recording the problems on your screen. This will help me to know how to find the problem more clearly.

**Comment by 2fix4u** [comment]
Same issue here, Chrome works FF not. Anchor navigation leads to new tab/window instead of scrolling up/down.
Btw: I can't change the ms for Smooth Scroll any more:

![grafik](https://github.com/user-attachments/assets/6dc08c1a-1db2-41de-bb97-4f2f173fbe23)

**Comment by tmumm** [comment]
I've found the same thing, you can see on my test site:  https://capture.dropbox.com/oZ5sLSd6D25iYAjE
That was me scrolling down as normal on the site here:  https://www.thirdsun.site/
This is only an issue in Chrome for me.

**Comment by sonvnn** [comment]
@Joomlaplates @WM-Loose @tmumm I fixed this issue at https://github.com/templaza/astroid-framework/commit/0dade23004d255c04b2bdcef7832d172ad143cc9
I also brought the `Scroll Speed` option back. 
Please help me download v3-branch and retest again. Hope you like it.

**Comment by WM-Loose** [comment]
Test positiv :-)
Now it works as it should.

**Comment by Joomlaplates** [comment]
Yes it working now.
Thank you Sonny

**Comment by WM-Loose** [comment]
Hi Sonny,
I just realized that there is still a problem. If smoothscroll is activated, scrolling in the offcanvas window no longer works. Only when smoothscroll is deactivated can you scroll up and down in the offcanvas window again with the mouse wheel. 
Unfortunately, I only just noticed it.

**Comment by sonvnn** [comment]
Thank you! I will check it and response asap

**Comment by sonvnn** [comment]
@WM-Loose I fixed issue of Smooth Scroll on Off Canvas at https://github.com/templaza/astroid-framework/commit/38b57be051d1e1fd7d16e47278dd207fa3594e17

Please help me download v3-branch and retest it.

**Comment by WM-Loose** [comment]
It works perfectly now. Thank you very much Sonny.
But I had to find the path to the PHP file first :-) For all users who don't want to search. 
The PHP file is here: myjoomla/libraries/astroid/framework/frontend/offcanvas.php
Sonny, you are great and solved it quickly as always.

**Comment by Joomlaplates** [comment]
Hi Sonny, yes its working now.
Thank you so much
